### ISSUE TITLE
base-url flag doesn't work properly

### ISSUE THREAD

**Issue by erks** [newrelic/check_docker#7]
Looks like the base-url flag isn't parsed properly making it impossible to override the default.  Also, the program actually fails if the docker daemon isn't listening on the default endpoint (http://localhost:2375).

expected:
```bash
$ ./check_docker -base-url="https://$(boot2docker ip):2376"
CRITICAL: Get https://192.168.59.103:2376/containers/json: x509: certificate signed by unknown authority
```

actual:
```bash
$ ./check_docker -base-url="https://$(boot2docker ip):2376"
CRITICAL: cannot connect to Docker endpoint
```

**Comment by didip** [comment]
This issue is fixed here: https://github.com/newrelic/check_docker/commit/48873e39162f119b19740e82a767079a57bbdfa1
